### ISSUE TITLE
installation from pip fails with an error on python 3.12.x

### ISSUE THREAD

**Issue by devdattaT** [wemap/pysupercluster#15]
I have Python 3.12.3 on an Ubuntu 24.04 system, and when I run `pip install pysupercluster`, it fails with an error `AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'

The complete example is as follows:

> dev@lpt-23-acer:/tmp$ mkdir demo && cd demo
> dev@lpt-23-acer:/tmp/demo$ python3 -m venv env
> dev@lpt-23-acer:/tmp/demo$ source env/bin/activate
> (env) dev@lpt-23-acer:/tmp/demo$ pip install pysupercluster
> Collecting pysupercluster
>   Using cached pysupercluster-0.7.7.tar.gz (8.2 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Installing backend dependencies ... done
>   Preparing metadata (pyproject.toml) ... error
>   error: subprocess-exited-with-error
> 
>   × Preparing metadata (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [60 lines of output]
>       running dist_info
>       creating /tmp/pip-modern-metadata-qk2t3p8h/pysupercluster.egg-info
>       writing /tmp/pip-modern-metadata-qk2t3p8h/pysupercluster.egg-info/PKG-INFO
>       writing dependency_links to /tmp/pip-modern-metadata-qk2t3p8h/pysupercluster.egg-info/dependency_links.txt
>       writing requirements to /tmp/pip-modern-metadata-qk2t3p8h/pysupercluster.egg-info/requires.txt
>       writing top-level names to /tmp/pip-modern-metadata-qk2t3p8h/pysupercluster.egg-info/top_level.txt
>       writing manifest file '/tmp/pip-modern-metadata-qk2t3p8h/pysupercluster.egg-info/SOURCES.txt'
>       Traceback (most recent call last):
>         File "/tmp/demo/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>           main()
>         File "/tmp/demo/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/demo/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
>           return hook(metadata_directory, config_settings)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 368, in prepare_metadata_for_build_wheel
>           self.run_setup()
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
>           super().run_setup(setup_script=setup_script)
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
>           exec(code, locals())
>         File "<string>", line 24, in <module>
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 108, in setup
>           return distutils.core.setup(**attrs)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
>           return run_commands(dist)
>                  ^^^^^^^^^^^^^^^^^^
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
>           dist.run_commands()
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 964, in run_commands
>           self.run_command(cmd)
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 945, in run_command
>           super().run_command(command)
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
>           cmd_obj.run()
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/command/dist_info.py", line 92, in run
>           self.egg_info.run()
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 310, in run
>           self.find_sources()
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 318, in find_sources
>           mm.run()
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 539, in run
>           self.add_defaults()
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 577, in add_defaults
>           sdist.add_defaults(self)
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
>           super().add_defaults()
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults
>           self._add_defaults_ext()
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 334, in _add_defaults_ext
>           build_ext = self.get_finalized_command('build_ext')
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 303, in get_finalized_command
>           cmd_obj.ensure_finalized()
>         File "/tmp/pip-build-env-1glej812/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
>           self.finalize_options()
>         File "<string>", line 18, in finalize_options
>       AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.

**Comment by ghost** [comment]
Experiencing the same.  Wondering if @jlaine is still maintaining this package.
